spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: billing_reports
      
  application:
    name: USERS-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898
